---
webhook_urls:
  description: 'Hash of webhooks'
  type: 'object'
  required: true
  additionalProperties: true
  properties:
    webhook:
      description: 'The webhook given to you by Teams'
      type: 'string'
